Update mftest with Docker build support

diff --git a/buildroot/share/git/mftest b/buildroot/share/git/mftest
--- a/buildroot/share/git/mftest
+++ b/buildroot/share/git/mftest
@@ -23,109 +23,120 @@ ISEXEC='^exec_'
 ISCONT='\\ *$'
 
 # Get the environment and test number from the command
-TESTENV=${1:-'-'}
-CHOICE=${2:-0}
+TESTENV='-'
+CHOICE=0
 AUTOENV=0
 
-# Allow shorthand for test name
+usage() {
+  echo -e "$(basename $0) : Marlin Firmware test, build, and upload\n"
+  echo "Usage: $(basename $0) ................. Select env and test to apply / run"
+  echo "       $(basename $0) [-y] env ........ Select a test for env to apply / run"
+  echo "       $(basename $0) [-y] env test ... Apply / run the specified env test"
+  echo "       $(basename $0) -b [variant] .... Auto-build the specified variant"
+  echo "       $(basename $0) -u [variant] .... Auto-build and upload the specified variant"
+  echo
+  echo "env shortcuts: tree due esp lin lpc|lpc8 lpc9 m128 m256|mega stm|f1 f4 f7 s6 teensy|t31|t32 t35|t36 t40|t41"
+}
+
+while getopts 'abmn:rt:vy123' flag; do
+  case "${flag}" in
+    a) AUTO_BUILD=1            ; echo "Get target via auto-build..." ;;
+    t) TEST_TARGET="${OPTARG}" ; echo "Got a target: $TEST_TARGET"   ;;
+    n) CHOICE="${OPTARG}"      ; echo "Got a number: $CHOICE"        ;;
+    r) REBUILD=1               ; echo "Rebuilding previous..."       ;;
+    m) USE_MAKE=1              ; echo "Using make with Docker..."    ;;
+    y) BUILD_YES='Y'           ; echo "Build will initiate..."       ;;
+    v) verbose='true' ;;
+   \d) echo "Number as flag?" ;;
+ -h|*) usage ; exit 1 ;;
+  esac
+done
+
+if ((REBUILD)); then
+  # Build with the last-built env
+  [[ -f "$STATE_FILE" ]] || { echo "No previous (-r) build state found." ; exit 1 ; }
+  read TESTENV <"$STATE_FILE"
+  pio run -d . -e $TESTENV
+  exit
+fi
+
 case $TESTENV in
-    tree) pio run -d . -e include_tree ; exit 1 ;;
-     due) TESTENV='DUE' ;;
-     esp) TESTENV='esp32' ;;
-    lin*) TESTENV='linux_native' ;;
- lpc?(8)) TESTENV='LPC1768' ;;
-    lpc9) TESTENV='LPC1769' ;;
-    m128) TESTENV='mega1280' ;;
-    m256) TESTENV='mega2560' ;;
-    mega) TESTENV='mega2560' ;;
-     stm) TESTENV='STM32F103RE' ;;
-      f1) TESTENV='STM32F103RE' ;;
-      f4) TESTENV='STM32F4' ;;
-      f7) TESTENV='STM32F7' ;;
-      s6) TESTENV='FYSETC_S6' ;;
-  teensy) TESTENV='teensy31' ;;
-     t31) TESTENV='teensy31' ;;
-     t32) TESTENV='teensy31' ;;
-     t35) TESTENV='teensy35' ;;
-     t36) TESTENV='teensy35' ;;
-     t40) TESTENV='teensy41' ;;
-     t41) TESTENV='teensy41' ;;
-
--h|--help)  echo -e "$(basename $0) : Marlin Firmware test, build, and upload\n"
-            echo "Usage: $(basename $0) ................. Select env and test to apply / run"
-            echo "       $(basename $0) [-y] env ........ Select a test for env to apply / run"
-            echo "       $(basename $0) [-y] env test ... Apply / run the specified env test"
-            echo "       $(basename $0) -b [variant] .... Auto-build the specified variant"
-            echo "       $(basename $0) -u [variant] .... Auto-build and upload the specified variant"
-            echo
-            echo "env shortcuts: tree due esp lin lpc|lpc8 lpc9 m128 m256|mega stm|f1 f4 f7 s6 teensy|t31|t32 t35|t36 t40|t41"
-            exit
-            ;;
-
-          # Build with the last-built env
-      -r) [[ -f "$STATE_FILE" ]] || { echo "No previous (-r) build state found." ; exit 1 ; }
-          read TESTENV <"$STATE_FILE"
-          pio run -d . -e $TESTENV
-          exit
-          ;;
-
-   -[bu]) MB=$( grep -E "^\s*#define MOTHERBOARD" Marlin/Configuration.h | awk '{ print $3 }' | $SED 's/BOARD_//' )
-          [[ -z $MB ]] && { echo "Error - Can't read MOTHERBOARD setting." ; exit 1 ; }
-          BLINE=$( grep -E "define\s+BOARD_$MB\b" Marlin/src/core/boards.h )
-          BNUM=$( $SED -E 's/^.+BOARD_[^ ]+ +([0-9]+).+$/\1/' <<<"$BLINE" )
-          BDESC=$( $SED -E 's/^.+\/\/ *(.+)$/\1/' <<<"$BLINE" )
-          [[ -z $BNUM ]] && { echo "Error - Can't find $MB in boards list." ; exit 1 ; }
-          readarray -t ENVS <<< $( grep -EA1 "MB\(.*\b$MB\b.*\)" Marlin/src/pins/pins.h | grep -E '#include.+//.+env:.+' | grep -oE 'env:[^ ]+' | $SED -E 's/env://' )
-          [[ -z $ENVS ]] && { echo "Error - Can't find target(s) for $MB ($BNUM)." ; exit 1 ; }
-          ECOUNT=${#ENVS[*]}
-
-          if [[ $ECOUNT == 1 ]]; then
-            TARGET=$ENVS
-          else
-            if [[ $CHOICE == 0 ]]; then
-              #
-              # List env names and numbers. Get selection.
-              #
-              echo "Available targets for \"$BDESC\" | $MB ($BNUM):"
-
-              IND=0 ; for ENV in "${ENVS[@]}"; do let IND++ ; echo " $IND) $ENV" ; done
-
-              if [[ $ECOUNT > 1 ]]; then
-                for (( ; ; ))
-                do
-                  read -p "Select a target for '$MB' (1-$ECOUNT) : " CHOICE
-                  [[ -z "$CHOICE" ]] && { echo '(canceled)' ; exit 1 ; }
-                  [[ $CHOICE =~ $ISNUM ]] && ((CHOICE >= 1 && CHOICE <= ECOUNT)) && break
-                  echo ">>> Invalid environment choice '$CHOICE'."
-                done
-                echo
-              fi
-            else
-              echo "Detected \"$BDESC\" | $MB ($BNUM)."
-              [[ $CHOICE > $ECOUNT ]] && { echo "Environment selection out of range." ; exit 1 ; }
-            fi
-            TARGET="${ENVS[$CHOICE-1]}"
-            echo "Selected $TARGET"
-          fi
-
-          echo "$TARGET" >"$STATE_FILE"
-
-          if [[ $TESTENV == "-u" ]]; then
-            echo "Build/Uploading environment $TARGET for board $MB ($BNUM)..." ; echo
-            pio run -t upload -e $TARGET
-          else
-            echo "Building environment $TARGET for board $MB ($BNUM)..." ; echo
-            pio run -e $TARGET
-          fi
-          exit
-          ;;
-
-          # The -y flag may come first
-      -y) TESTENV=${2:-'-'} ; CHOICE=${3:-0} ;;
-
-  -[a-z]) echo "Unknown flag $TESTENV" ; exit 1 ;;
-       -) ;;
+   tree) pio run -d . -e include_tree ; exit 1 ;;
+    due) TESTENV='DUE' ;;
+    esp) TESTENV='esp32' ;;
+   lin*) TESTENV='linux_native' ;;
+lpc?(8)) TESTENV='LPC1768' ;;
+   lpc9) TESTENV='LPC1769' ;;
+   m128) TESTENV='mega1280' ;;
+   m256) TESTENV='mega2560' ;;
+   mega) TESTENV='mega2560' ;;
+    stm) TESTENV='STM32F103RE' ;;
+     f1) TESTENV='STM32F103RE' ;;
+     f4) TESTENV='STM32F4' ;;
+     f7) TESTENV='STM32F7' ;;
+     s6) TESTENV='FYSETC_S6' ;;
+ teensy) TESTENV='teensy31' ;;
+    t31) TESTENV='teensy31' ;;
+    t32) TESTENV='teensy31' ;;
+    t35) TESTENV='teensy35' ;;
+    t36) TESTENV='teensy35' ;;
+    t40) TESTENV='teensy41' ;;
+    t41) TESTENV='teensy41' ;;
 esac
+
+if ((AUTO_BUILD)); then
+  #
+  # List environments that apply to the current MOTHERBOARD.
+  #
+  echo ; echo "Auto Build..."
+  MB=$( grep -E "^\s*#define MOTHERBOARD" Marlin/Configuration.h | awk '{ print $3 }' | $SED 's/BOARD_//' )
+  [[ -z $MB ]] && { echo "Error - Can't read MOTHERBOARD setting." ; exit 1 ; }
+  BLINE=$( grep -E "define\s+BOARD_$MB\b" Marlin/src/core/boards.h )
+  BNUM=$( $SED -E 's/^.+BOARD_[^ ]+ +([0-9]+).+$/\1/' <<<"$BLINE" )
+  BDESC=$( $SED -E 's/^.+\/\/ *(.+)$/\1/' <<<"$BLINE" )
+  [[ -z $BNUM ]] && { echo "Error - Can't find $MB in boards list." ; exit 1 ; }
+  ENVS=( $( grep -EA1 "MB\(.*\b$MB\b.*\)" Marlin/src/pins/pins.h | grep -E '#include.+//.+env:[^ ]+' | grep -oE 'env:[^ ]+' | $SED -E 's/env://' ) )
+  [[ -z $ENVS ]] && { echo "Error - Can't find target(s) for $MB ($BNUM)." ; exit 1 ; }
+  ECOUNT=${#ENVS[*]}
+
+  if [[ $ECOUNT == 1 ]]; then
+    TARGET=$ENVS
+  else
+    if [[ $CHOICE == 0 ]]; then
+      # List env names and numbers. Get selection.
+      echo "Available targets for \"$BDESC\" | $MB ($BNUM):"
+
+      IND=0 ; for ENV in "${ENVS[@]}"; do let IND++ ; echo " $IND) $ENV" ; done
+
+      if [[ $ECOUNT > 1 ]]; then
+        for (( ; ; ))
+        do
+          read -p "Select a target for '$MB' (1-$ECOUNT) : " CHOICE
+          [[ -z "$CHOICE" ]] && { echo '(canceled)' ; exit 1 ; }
+          [[ $CHOICE =~ $ISNUM ]] && ((CHOICE >= 1 && CHOICE <= ECOUNT)) && break
+          echo ">>> Invalid environment choice '$CHOICE'."
+        done
+        echo
+      fi
+    else
+      echo "Detected \"$BDESC\" | $MB ($BNUM)."
+      [[ $CHOICE > $ECOUNT ]] && { echo "Environment selection out of range." ; exit 1 ; }
+    fi
+    TARGET="${ENVS[$CHOICE-1]}"
+    echo "Selected $TARGET"
+  fi
+
+  echo "$TARGET" >"$STATE_FILE"
+
+  if [[ $TESTENV == "-u" ]]; then
+    echo "Build/Uploading environment $TARGET for board $MB ($BNUM)..." ; echo
+    pio run -t upload -e $TARGET
+  else
+    echo "Building environment $TARGET for board $MB ($BNUM)..." ; echo
+    pio run -e $TARGET
+  fi
+  exit
+fi
 
 #
 # List available tests and ask for selection
@@ -172,7 +183,7 @@ if [[ $CHOICE == 0 ]]; then
     while IFS= read -r LINE
     do
       if [[ $LINE =~ $ISEXEC ]]; then
-        DESC=$( "$SED" -E 's/^.+"(.*)".*$/\1/g' <<<"$LINE" )
+        DESC=$( "$SED" -E 's/^exec_test \$1 \$2 "(.*)" "\$3".*$/\1/g' <<<"$LINE" )
         (( ++IND < 10 )) && echo -n " "
         echo " $IND) $DESC"
       fi
@@ -221,9 +232,6 @@ echo "$OUT" | {
 # Make clear it's a TEST
 opt_set CUSTOM_MACHINE_NAME "\"$TESTENV-tests ($CHOICE)\""
 
-# Get a -y parameter the lazy way
-[[ "$2" == "-y" || "$3" == "-y" ]] && BUILD_YES='Y'
-
 # Build the test too?
 if [[ $BUILD_YES != 'Y' ]]; then
   echo
@@ -231,6 +239,7 @@ if [[ $BUILD_YES != 'Y' ]]; then
 fi
 
 [[ $BUILD_YES == 'Y' || $BUILD_YES == 'Yes' ]] && {
-  pio run -d . -e $TESTENV
+  ((USE_MAKE)) && make tests-single-local TEST_TARGET=$TESTENV ONLY_TEST=1
+  ((USE_MAKE)) || pio run -d . -e $TESTENV
   echo "$TESTENV" >"$STATE_FILE"
 }
