🧑‍💻 Build examples --output option (#27389)

diff --git a/buildroot/bin/build_example b/buildroot/bin/build_example
--- a/buildroot/bin/build_example
+++ b/buildroot/bin/build_example
@@ -4,13 +4,32 @@
 #
 #  build_example  -b|--base=<path>    - Configurations root folder (e.g., ./.pio/build-BRANCH)
 #                 -c|--config=<rel>   - Sub-path of the configs to build (within config/examples)
-#                [-e|--export=N]      - Set CONFIG_EXPORT before build and export into the config folder
-#                [-n|--nofail]        - Don't stop on a failed build
-#                [-r|--reveal]        - Reveal the config folder after the build
-#                [-h|--help]          - Print usage and exit
+#                [-e|--export=N]      - Set CONFIG_EXPORT before build and export
 #                [-a|--archive]       - Archive the build (to the export location)
+#                [-o|--output]        - Redirect export / archiving to another location
+#                                       (By default export to origin config folder)
+#                [-f|--nofail]        - Don't stop on a failed build
+#                [-w|--nowarn]        - Suppress warnings with extra config options
+#                [-r|--reveal]        - Reveal the config/export folder after the build
+#                [-h|--help]          - Print usage and exit
 #                [--allow]            - Allow this script to run standalone
 #
+
+usage() { echo "Usage:
+
+build_example  -b|--base=<path>    - Configurations root folder (e.g., ./.pio/build-BRANCH)
+               -c|--config=<rel>   - Sub-path of the configs to build (within config/examples)
+              [-e|--export=N]      - Set CONFIG_EXPORT before build and export
+              [-a|--archive]       - Archive the build (to the export location)
+              [-o|--output]        - Redirect export / archiving to another location
+                                     (By default export to origin config folder)
+              [-f|--nofail]        - Don't stop on a failed build
+              [-w|--nowarn]        - Suppress warnings with extra config options
+              [-r|--reveal]        - Reveal the config/export folder after the build
+              [-h|--help]          - Print usage and exit
+              [--allow]            - Allow this script to run standalone
+"
+}
 
 HERE=`dirname $0`
 
@@ -28,14 +47,16 @@ CONFIG=
 REVEAL=
 EXPNUM=
 NOFAIL=
-while getopts 'ab:c:e:hinr-:' OFLAG; do
+OUTBASE=
+while getopts 'ab:c:e:fhio:r-:' OFLAG; do
   case "${OFLAG}" in
     a) ARCHIVE=1 ;;
     b) BASE="${OPTARG%/}" ;;
     c) CONFIG="${OPTARG%/}" ;;
     e) EXPNUM="$OPTARG" ;;
+    o) OUTBASE="${OPTARG%/}" ;;
     h) EXIT_USAGE=1 ; break ;;
-    n) NOFAIL=1 ;;
+    f) NOFAIL=1 ;;
     r) REVEAL=1 ;;
     -) IFS="=" read -r ONAM OVAL <<< "$OPTARG"
        case "$ONAM" in
@@ -44,21 +65,30 @@ while getopts 'ab:c:e:hinr-:' OFLAG; do
            base) BASE="${OVAL%/}" ;;
          config) CONFIG="${OVAL%/}" ;;
          export) EXPNUM="$OVAL" ;;
+         output) OUTBASE="${OVAL%/}" ;;
            help) EXIT_USAGE=1 ; break ;;
          nofail) NOFAIL=1 ;;
          reveal) REVEAL=1 ;;
               *) EXIT_USAGE=2 ; echo "$SELF: unrecognized option \`--$ONAM'" ; break ;;
        esac
        ;;
+    *) EXIT_USAGE=2 ; break ;;
   esac
 done
 
 # Must be called from another script (or with --allow)
 [[ $ALLOW || $SHLVL -gt 2 ]] || { echo "Don't call this script directly, use build_all_examples instead." ; exit 1 ; }
 
+# Exit with helpful usage information
+((EXIT_USAGE)) && { usage ; let EXIT_USAGE-- ; exit $EXIT_USAGE ; }
+
 # -b|--base and -c|--config are required
 [[ -z $BASE ]] && { echo "-b|--base is required" ; exit 1 ; }
 [[ -z $CONFIG ]] && { echo "-c|--config is required" ; exit 1 ; }
+
+# Expand ~ to $HOME in provided arguments
+BASE=${BASE/#\~/$HOME}
+CONFIG=${CONFIG/#\~/$HOME}
 
 # Make sure the examples exist
 SUB1="$BASE/config/examples"
@@ -71,12 +101,21 @@ SUB="$SUB1/$CONFIG"
 # ...and contains Configuration.h or Configuration_adv.h
 [[ -n $(compgen -G "$SUB/Configuration*.h") ]] || { echo "No configuration files found in $SUB" ; exit 1 ; }
 
+# Get the location for exports and archives
+if [[ -n $OUTBASE ]]; then
+  ARCSUB="${OUTBASE/#\~/$HOME}/$CONFIG"
+  mkdir -p "$ARCSUB"
+else
+  ARCSUB="$SUB"
+fi
+
 # Delete any config files from previous builds
 rm -f Marlin/_Bootscreen.h Marlin/_Statusscreen.h
 
 # Copy configurations into the Marlin folder
 echo "Getting configuration files from $SUB"
-cp "$BASE/config/default"/*.h "$SUB"/*.h Marlin/ 2>/dev/null
+cp "$BASE"/config/default/*.h Marlin/
+cp "$SUB"/*.h Marlin/
 
 rm -f Marlin/Config.h Marlin/Config-export.h
 
@@ -87,6 +126,9 @@ IFS=$'\n'; set -f
 $SED -i~ -e "20,30{/#error/d}" Marlin/Configuration.h
 rm Marlin/Configuration.h~
 unset IFS; set +f
+
+# Hide several warnings when not exporting
+[[ -z $EXPNUM ]] && CLEANER=1
 
 # Suppress fatal warnings
 if ((CLEANER)); then
@@ -104,11 +146,13 @@ if ((CLEANER)); then
   opt_add NO_HOMING_CURRENT_WARNING
 fi
 
+# Possible exported file names (in the build folder)
 ENAME=("-name" "marlin_config.json" \
   "-o" "-name" "config.ini" \
   "-o" "-name" "schema.json" \
   "-o" "-name" "schema.yml")
 
+# Possible built firmware names (in the build folder)
 BNAME=("-type" "f" \
        "-name" 'firmware*.hex' \
   "-o" "-name" "firmware*.bin" \
@@ -139,29 +183,32 @@ set -e
 # Copy exports back to the configs
 if [[ -n $EXPNUM ]]; then
   annc "Exporting $EXPNUM"
-  [[ -f Marlin/Config-export.h ]] && { cp Marlin/Config-export.h "$SUB"/Config.h ; }
-  find "$BUILD" "${ENAME[@]}" -exec cp "{}" "$SUB" \;
+  [[ -f Marlin/Config-export.h ]] && { cp Marlin/Config-export.h "$ARCSUB"/Config.h ; }
+  find "$BUILD" "${ENAME[@]}" -exec cp "{}" "$ARCSUB" \;
 fi
 
+# Copy potential firmware files into the config folder
+# TODO: Consider firmware that needs an STM32F4_UPDATE folder.
+#       Currently only BOARD_CREALITY_F401RE env:STM32F401RE_creality
 if ((ARCHIVE)); then
   annc "Archiving"
   find "$BUILD" \( "${BNAME[@]}" \) -exec sh -c '
-    SUB="$1"
+    ARCSUB="$1"
     shift 1
     for file in "$@"; do
       cd "$(dirname "$file")"
       base=$(basename "$file")
-      tar -czf "$SUB/$base.tar.gz" "$base"
+      tar -czf "$ARCSUB/$base.tar.gz" "$base"
       rm "$base"
       cd - >/dev/null
     done
-  ' sh "$SUB" {} +
+  ' sh "$ARCSUB" {} +
 fi
 
 # Exit with error unless --nofail is set
 [[ $ERR -gt 0 && -z $NOFAIL ]] && exit $ERR
 
 # Reveal the configs after the build, if requested
-((REVEAL)) && { annc "Revealing $SUB" ; open "$SUB" ; }
+((REVEAL)) && { annc "Revealing $ARCSUB" ; open "$ARCSUB" ; }
 
 exit 0
