misc cleanup

diff --git a/buildroot/bin/build_all_examples b/buildroot/bin/build_all_examples
--- a/buildroot/bin/build_all_examples
+++ b/buildroot/bin/build_all_examples
@@ -3,42 +3,39 @@
 # build_all_examples
 #
 
-# Require gsed or sed
+GITREPO=https://github.com/MarlinFirmware/Configurations.git
+
+# Check dependencies
+which curl 1>/dev/null 2>&1 || { echo "curl not found! Please install it."; exit ; }
+which git 1>/dev/null 2>&1 || { echo "git not found! Please install it."; exit ; }
+
 SED=$(command -v gsed 2>/dev/null || command -v sed 2>/dev/null)
 [[ -z $SED ]] && { echo "No sed found, please install sed" ; exit 1 ; }
 
-echo "This script will attempt to build Marlin for all known configurations."
-echo "In case of failure, the current configuration remains in your repository."
-echo "To revert to your current version, run 'git checkout -f'."
-
-GITREPO=https://github.com/MarlinFirmware/Configurations.git
+# Check if called in the right location
+if [[ ! -e "Marlin/src" ]]; then
+  echo "This script must be called from a Marlin working copy with:"
+  echo " ./buildroot/bin/$self $1"
+  exit
+fi
 
 self=`basename "$0"`
 HERE=`dirname "$0"`
 
-# Check dependencies
-which curl 1>/dev/null 2>&1 || { echo "curl not found, please install it"; exit ; }
-which git 1>/dev/null 2>&1 || { echo "git not found, please install it"; exit ; }
-if [ -z "$1" ]; then
-  echo ""
-  echo "ERROR: "
-  echo "  Expected parameter: $self base_branch [resume_point]"
-  echo "  with:"
-  echo "         base_branch              The branch in the Configuration repository to use"
-  echo "         resume_point             If not empty, resume building from this board"
-
+if [[ $# -lt 1 || $# -gt 2 ]]; then
+  echo "
+  Usage: $self base_branch [resume_point]
+         base_branch    Configuration branch to download and build
+         resume_point   Configuration path to start from"
   exit
 fi
 
-# Check if called in the right folder
-if [ ! -e "Marlin/src" ]; then
-  echo "This script must be called from the root folder of a Marlin repository, please navigate to this folder and call:"
-  echo "buildroot/ci-check/$self $1"
-  exit
-fi
+echo "This script downloads all Configurations and builds Marlin with each one."
+echo "On failure the last-built configs will be left in your working copy."
+echo "Restore your configs with 'git checkout -f' or 'git reset --hard HEAD'."
 
 # Check if the current repository has unmerged changes
-if [ -z "$2" ]; then
+if [[ -z $2 ]]; then
   git diff --quiet || { echo "Your current repository is not clean. Either commit your change or stash them, and re-run this script"; exit ; }
 else
   echo "Resuming from $2"
@@ -50,7 +47,7 @@ fi
 # Ok, let's do our stuff now
 # First extract the current temporary folder
 echo "Fetching configuration repository"
-if [ ! -e "$MFTEMP/README.md" ]; then
+if [[ ! -e "$MFTEMP/README.md" ]]; then
   git clone --depth 1 --single-branch --branch "$1" $GITREPO "$MFTEMP" || { echo "Failed to clone the configuration repository"; exit ; }
 fi
 
@@ -59,13 +56,10 @@ echo
 echo "Start building now..."
 echo "====================="
 shopt -s nullglob
-for config in $MFTEMP/config/examples/*/; do
-  [ -d "${config}" ] || continue
+for config in $MFTEMP/config/examples/**/; do
+  [[ -d $config ]] || continue
   base=`basename "$config"`
-  if [ ! -z "$2" ] && [ "$2" != "$base" ]; then
-    echo "Skipping $base..."
-    continue
-  fi
+  [[ ! -z $2 ]] && [[ $2 != $base ]] && { echo "Skipping $base..." ; continue ; }
   "$HERE/build_example" "internal" "$MFTEMP" "$base" || { echo "Failed to build $base"; exit ; }
 done
 
