one example per

diff --git a/buildroot/bin/build_example b/buildroot/bin/build_example
--- a/buildroot/bin/build_example
+++ b/buildroot/bin/build_example
@@ -10,25 +10,20 @@
 
 echo "Testing $3:"
 
-shopt -s nullglob
-for sub in $2/config/examples/$3/*/; do
-  [[ -d $sub ]] || continue
-  base=`basename "$sub"`
+SUB=$2/config/examples/$3
+[[ -d $SUB ]] || { echo "$SUB is not a good path" ; exit 1 ; }
 
-  if [[ ! -f $sub/Configuration.h ]] && [[ ! -f $sub/Configuration_adv.h ]]; then
-    echo "No configuration files found in $sub"
-    continue
-  fi
+compgen -G "${CONF}Con*.h" > /dev/null || { echo "No configuration files found in $SUB" ; exit 1 ; }
 
-  echo "Getting configuration files from $sub"
-  cp "$2/config/default"/*.h    Marlin/
-  cp "$sub"/Configuration.h     Marlin/ 2>/dev/null
-  cp "$sub"/Configuration_adv.h Marlin/ 2>/dev/null
-  cp "$sub"/_Bootscreen.h       Marlin/ 2>/dev/null
-  cp "$sub"/_Statusscreen.h     Marlin/ 2>/dev/null
+echo "Getting configuration files from $SUB"
+cp "$2/config/default"/*.h    Marlin/
+cp "$SUB"/Configuration.h     Marlin/ 2>/dev/null
+cp "$SUB"/Configuration_adv.h Marlin/ 2>/dev/null
+cp "$SUB"/_Bootscreen.h       Marlin/ 2>/dev/null
+cp "$SUB"/_Statusscreen.h     Marlin/ 2>/dev/null
 
-  echo "Building the firmware now..."
-  ./mftest -a || { echo "Failed"; exit 1; }
-done
+echo "Building the firmware now..."
+HERE=`dirname "$0"`
+$HERE/mftest -a || { echo "Failed"; exit 1; }
 
 echo "Success"
