dependency hell sorted

diff --git a/buildroot/bin/build_example b/buildroot/bin/build_example
--- a/buildroot/bin/build_example
+++ b/buildroot/bin/build_example
@@ -32,20 +32,8 @@ for sub in $2/config/examples/$3/*/; do
   cp "$sub"/_Bootscreen.h       Marlin/ 2>/dev/null
   cp "$sub"/_Statusscreen.h     Marlin/ 2>/dev/null
 
-  # Shamelessly copied from mftest script, skimmed the dependencies
-  MB=$( grep -E "^\s*#define MOTHERBOARD" Marlin/Configuration.h | awk '{ print $3 }' | $SED 's/BOARD_//' )
-  [[ -z $MB ]] && { echo "Error - Can't read MOTHERBOARD setting." ; exit 2 ; }
-  BLINE=$( grep -E "define\s+BOARD_$MB\b" Marlin/src/core/boards.h )
-  BNUM=$( $SED -E 's/^.+BOARD_[^ ]+ +([0-9]+).+$/\1/' <<<"$BLINE" )
-  BDESC=$( $SED -E 's/^.+\/\/ *(.+)$/\1/' <<<"$BLINE" )
-  [[ -z $BNUM ]] && { echo "Error - Can't find $MB in boards list." ; exit 2 ; }
-  ENVS=( $( grep -EA1 "MB\(.*\b$MB\b.*\)" Marlin/src/pins/pins.h | grep -E "#include.+//.+(env|$SYS):[^ ]+" | grep -oE "(env|$SYS):[^ ]+" | $SED -E "s/(env|$SYS)://" ) )
-  [[ -z $ENVS ]] && { errout "Error - Can't find target(s) for $MB ($BNUM)." ; exit 2 ; }
-  ECOUNT=${#ENVS[*]}
-
-  echo "Deduced env: $ENVS ($ECOUNT)"
   echo "Building the firmware now..."
-  platformio run --environment $ENVS || { echo "Failed"; exit 1; }
+  ./mftest -a || { echo "Failed"; exit 1; }
 done
 
 echo "Success"
