Testing split up config

diff --git a/buildroot/bin/mftest b/buildroot/bin/mftest
--- a/buildroot/bin/mftest
+++ b/buildroot/bin/mftest
@@ -157,7 +157,10 @@ if ((AUTO_BUILD)); then
   esac
   echo ; echo -n "Auto " ; ((AUTO_BUILD == 2)) && echo "Upload..." || echo "Build..."
   MB=$( grep -E "^\s*#define MOTHERBOARD" Marlin/Configuration.h | awk '{ print $3 }' | $SED 's/BOARD_//;s/\r//' )
-  [[ -z $MB ]] && { echo "Error - Can't read MOTHERBOARD setting." ; exit 1 ; }
+  if [[ -z $MB ]]; then
+    MB=$( grep -E "^\s*#define MOTHERBOARD" Marlin/config/machine.h | awk '{ print $3 }' | $SED 's/BOARD_//;s/\r//' )
+    [[ -z $MB ]] && { echo "Error - Can't read MOTHERBOARD setting." ; exit 1; }
+  fi
   BLINE=$( grep -E "define\s+BOARD_$MB\b" Marlin/src/core/boards.h )
   BNUM=$( $SED -E 's/^.+BOARD_[^ ]+ +([0-9]+).+$/\1/' <<<"$BLINE" )
   BDESC=$( $SED -E 's/^.+\/\/ *(.+)$/\1/' <<<"$BLINE" )
diff --git a/buildroot/bin/opt_disable b/buildroot/bin/opt_disable
--- a/buildroot/bin/opt_disable
+++ b/buildroot/bin/opt_disable
@@ -11,5 +11,11 @@ for opt in "$@" ; do
     "${SED}" -i "/^\(\s*\)\(#define\s\+${opt}\b\s\?\)\(\s\s\)\?/{s//\1\/\/\2/;h};\${x;/./{x;q0};x;q9}" Marlin/$FN.h && DID=1
     ((DID||FOUND)) || { grep -E "^\s*//\s*#define\s+${opt}\b" Marlin/$FN.h >/dev/null && FOUND=1 ; }
   done
-  ((DID||FOUND)) || (echo "ERROR: $(basename $0) Can't find ${opt}" >&2 && exit 9)
+  if [[ -d Marlin/config ]]; then
+    for FN in Marlin/config/*.h; do
+      "${SED}" -i "/^\(\s*\)\(#define\s\+${opt}\b\s\?\)\(\s\s\)\?/{s//\1\/\/\2/;h};\${x;/./{x;q0};x;q9}" $FN && DID=1
+      ((DID||FOUND)) || { grep -E "^\s*//\s*#define\s+${opt}\b" $FN >/dev/null && FOUND=1 ; }
+    done
+  fi
+  ((DID||FOUND)) || { echo "WARNING: $(basename $0) Can't find ${opt}" >&2 ; exit 0 ; }
 done
diff --git a/buildroot/bin/opt_enable b/buildroot/bin/opt_enable
--- a/buildroot/bin/opt_enable
+++ b/buildroot/bin/opt_enable
@@ -7,9 +7,16 @@ SED=$(which gsed sed | head -n1)
 
 for opt in "$@" ; do
   DID=0 ; FOUND=0
+  PATT="/^\(\s*\)\/\/\(\s*\)\(#define\s\+${opt}\b\)\( \?\)/{s//\1\2\3\4\4\4/;h};\${x;/./{x;q0};x;q9}"
   for FN in Configuration Configuration_adv; do
-    "${SED}" -i "/^\(\s*\)\/\/\(\s*\)\(#define\s\+${opt}\b\)\( \?\)/{s//\1\2\3\4\4\4/;h};\${x;/./{x;q0};x;q9}" Marlin/$FN.h && DID=1
+    "${SED}" -i "$PATT" "Marlin/$FN.h" && DID=1
     ((DID||FOUND)) || { grep -E "^\s*#define\s+${opt}\b" Marlin/$FN.h >/dev/null && FOUND=1 ; }
   done
-  ((DID||FOUND)) || (echo "ERROR: $(basename $0) Can't find ${opt}" >&2 && exit 9)
+  if [[ -d Marlin/config ]]; then
+    for FN in Marlin/config/*.h; do
+      "${SED}" -i "$PATT" $FN && DID=1
+      ((DID||FOUND)) || { grep -E "^\s*#define\s+${opt}\b" $FN >/dev/null && FOUND=1 ; }
+    done
+  fi
+  ((DID||FOUND)) || { echo "ERROR: $(basename $0) Can't find ${opt}" >&2 ; exit 9 ; }
 done
diff --git a/buildroot/bin/opt_find b/buildroot/bin/opt_find
--- a/buildroot/bin/opt_find
+++ b/buildroot/bin/opt_find
@@ -23,11 +23,11 @@ esac
 
 while [[ $# > 0 ]]; do
   DID=0
-  for FN in Configuration Configuration_adv; do
-    FOUND=$( grep -HEn "^\s*${COMM}#define\s+[A-Z0-9_]*${1}" "Marlin/$FN.h" 2>/dev/null )
-    [[ -n "$FOUND" ]] && { echo "$FOUND" ; DID=1 ; }
+  for FN in Marlin/Configuration.h Marlin/Configuration_adv.h Marlin/config/*.h ; do
+    FOUND=$( grep -HEn "^\s*${COMM}#define\s+[A-Z0-9_]*${1}" "$FN" 2>/dev/null )
+    [[ -n "$FOUND" ]] && { echo "$FOUND" ; DID=1 ; break ; }
   done
-  ((DID)) || { echo "ERROR: ${MYNAME} - No ${TYPE}match for ${1}" ; exit 9; }
+  ((DID)) || { echo "ERROR: ${MYNAME} - No ${TYPE}match for ${1}" ; exit 9 ; }
   shift
   echo
 done
diff --git a/buildroot/bin/opt_set b/buildroot/bin/opt_set
--- a/buildroot/bin/opt_set
+++ b/buildroot/bin/opt_set
@@ -10,8 +10,13 @@ while [[ $# > 1 ]]; do
   for FN in Configuration Configuration_adv; do
     "${SED}" -i "/^\(\s*\)\/*\s*\(#define\s\+${1}\b\) *\(.*\)$/{s//\1\2 ${2} \/\/ \3/;h};\${x;/./{x;q0};x;q9}" Marlin/$FN.h && DID=1
   done
+  if [[ -d Marlin/config ]]; then
+    for FN in Marlin/config/*.h; do
+      "${SED}" -i "/^\(\s*\)\/*\s*\(#define\s\+${1}\b\) *\(.*\)$/{s//\1\2 ${2} \/\/ \3/;h};\${x;/./{x;q0};x;q9}" $FN && DID=1
+    done
+  fi
   ((DID)) ||
     eval "echo '#define ${1} ${2}' >>Marlin/Configuration.h" ||
-      (echo "ERROR: opt_set Can't set or add ${1}" >&2 && exit 9)
+      { echo "WARNING: opt_set Can't set or add ${1}" >&2 ; exit 0 ; }
   shift 2
 done
